#THIS IS A EXERCISE FOR UNDERSTANDING BASICS OF NUMPY

#BASIC MATRIX CREATION AND RANDOM

In [2]:
#Import Numpy
import numpy as np

In [4]:
#Numpy array of 10 zeroes
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#Numpy array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
#Numpy array of 10 fives
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [16]:
#Numpy Array Of Integers From 10 To 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [22]:
#Numpy Array Of Integers Fron 10 To 50 Only Even Numbers
#Complex Way
np.arange(10,51)[np.arange(10,51)%2==0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [24]:
#Simple Way
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [30]:
#Create A 3x3 Matrix With Values Ranging Fron 0 TO 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
#3X3 Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#Random Number Between O and 1
np.random.rand(1)

array([0.18041058])

In [38]:
#Generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([ 1.29975003, -0.61689999,  0.72500256,  0.71869268,  0.71678936,
       -0.06034187,  0.51809016,  0.13619478, -0.15698091, -0.14338069,
       -1.28409417, -0.38775391,  2.54296541, -0.46222466, -0.4085969 ,
       -1.79063952,  0.31843847,  1.32875492, -0.35897454,  0.62279632,
        0.27698785,  0.40793788, -0.1386969 ,  1.62492642,  0.24416167])

In [42]:
#Create An Array Of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#NUMPY INDEXING AND SELECTION

In [44]:
#Test MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [48]:
#SUB MATRIX FROM 3rd Column and 2nd Row  To 5th Column And 5th Row
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [52]:
#Extract 20 From Mat
mat[3:4,4:]

array([[20]])

In [54]:
#Extract 2,7,12 From Mat
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [58]:
#Extract 5th Row
mat[4:]

array([[21, 22, 23, 24, 25]])

In [64]:
#Get Sum Of All Values In Mat
sum(sum(mat))

325

In [66]:
#Standard Deviation Of Values In Mat
np.std(mat)

7.211102550927978

In [68]:
#Get Sum Of ALl Columns In Mat
sum(mat)

array([55, 60, 65, 70, 75])

#THANK YOU 

#CREATED BY SHAURYA MITTAL